### ISSUE TITLE
Pricing request table management - Part B [Logic] 

### ISSUE THREAD

**Issue by Dagolin** [telecom4good/admin-telecom4good-org#18]
- List : 	Retrieve and show data from Smartsheet API
- Add :      Add data into Smartsheet via API after submit
- Edit:  Update data on Smartsheet via API after submit
- Delete: Delete data on Smartsheet via API

**Comment by pbishop16** [comment]
Issue broken down into issues #24, #25, #26. Deletion will be excluded for now.
