### ISSUE TITLE
Staging server

### ISSUE THREAD

**Issue by Dagolin** [telecom4good/admin-telecom4good-org#3]
Prepare staging server on CPanel

https://drive.google.com/drive/folders/0B3jq_BOZVDJkYlJoTWNVeERzUDQ

**PHP on CPanel (5.4) is behind our project requirement (5.6)**

We have to wait till the new t4g front page take over the Wordpress site to update PHP, and create our own staging server at 'adminstaging.telecom4good.org'

**Comment by Dagolin** [comment]
We have to wait till the new t4g front page take over the Wordpress site to update PHP, and create our own staging server at 'adminstaging.telecom4good.org'

**Comment by dataguy23us** [comment]
Dago. The admin.telecom4good.org is available. I believe that Paul has already uploaded the information and it is available for review. Username and password is the same as the cloudpen account for now

**Comment by Dagolin** [comment]
Cool, we use admin.telecom4good.org as our Admin Portal?

I am thinking that maybe we can skip the staging part.

Pros

-  Faster development

Cons

- Without staging server, unknown/tested bug might cause damage to our data.

Just a idea, so far we will keep follow master&staging standard workflow

**Comment by pbishop16** [comment]
Dago,

I agree with your Pros/Cons. I will see if I can establish a basic staging server.

**Comment by Dagolin** [comment]
@pbishop16 Many thanks, yet we still have to wait till the server is ready for PHP 5.6 :/

**Comment by pbishop16** [comment]
Dago, yeah thanks for the reminders. I got a little ahead of myself.

**Comment by Dagolin** [comment]
@pbishop16 Just a friendly reminder :)

**Comment by pbishop16** [comment]
The staging server has been set at [staging-admin.telecom4good.org](http://staging-admin.telecom4good.org). Below are the basic configuration details:

1. Staging server established
     - primary code folder `admin_portal_staging`
     - app public files placed in public_html folder under folder `staging-admin.telecom4good.org`
2. .env set for staging environment
3. Staging database established named `admin_portal_official_staging`
4. `.htaccess` file adjusted to support Laravel framework and https redirect
5. SSL Cert configured using https://zerossl.com/ (cert is good for 90 days)
6. Domain PHP upgraded to version PHP 5.6

The most current dev branch version has been uploaded and configured for configuration validation purposes. Reference pull request #12 for admin and staff role login details.

I will seek more efficient ways to upload new code to the staging environment. All relevant files will be added to the [Telecom4good Admin Portal](https://drive.google.com/folderview?id=0B3jq_BOZVDJkYlJoTWNVeERzUDQ&usp=sharing) Google Drive folder.

Please let me know if there are any questions.
