### ISSUE TITLE
ISP provider management

### ISSUE THREAD

**Issue by Dagolin** [telecom4good/admin-telecom4good-org#8]
- Database table setup
- List with pagination
- User can add / edit / delete records
- Data validation
- Privileges

**Comment by pbishop16** [comment]
Still learning, but I will give this a go.

**Comment by Dagolin** [comment]
thanks for your contribution Paul! this is great. I will share anything I have known with you! I suggest that you can break this issue into small parts and solve with different PRs, it's up to you.

For `table setup`, I have prepared the migration file for table `t4g_isp`, after execute `php artisan migrate` you should have a table `t4g_isp`. if you feel like to change anything. 
```
php artisan make:migration update_t4g_isp_table --table=t4g_isp
```
You will have a new migration file in /database/migrations.

if you want to update schema, do something in your migration file like
```
$table->string('name', 50)->nullable()->change();
```
then run 
```
php artisan migrate
```

For migration commands, ref (Laravel migrations)[https://laravel.com/docs/5.2/migrations]

**Comment by Dagolin** [comment]
And of course, you may want to reference #11 (Thanks for you fast review again!) because these 2 issues are almost the same.

you will need to:

- Create routes for ISP management pages
- Build a controller `php artisan make:controller ISPController --resource`
- Build a model `php artisan make:model ISPModel`
- Create view files (just copy the old ones!)
- Coding :+1: 

If you have any question during developing with Laravel, just let me know! I will support as much as possible.

**Comment by pbishop16** [comment]
Dago, greatly appreciated. I will be sure to reach out if I get stuck.
